# Notebook to achieve some test

In [2]:
import numpy as np

mA1 = np.random.rand(4, 1)  # Example 4x1 matrix
mA2 = np.random.rand(4, 1)  # Example 4x1 matrix

deltaA = mA1.T - mA2  # This will produce a (4,4) matrix

print(deltaA)

[[-0.08257113  0.43155658  0.10972    -0.40152554]
 [ 0.04788025  0.56200796  0.24017138 -0.27107416]
 [ 0.26677129  0.780899    0.45906241 -0.05218312]
 [-0.4692178   0.04490991 -0.27692667 -0.78817221]]


In [3]:
N = 1024
Q = 2
n = np.expand_dims(np.arange(N),axis=1)
i = np.arange(Q+1)
n**i

array([[      1,       0,       0],
       [      1,       1,       1],
       [      1,       2,       4],
       ...,
       [      1,    1021, 1042441],
       [      1,    1022, 1044484],
       [      1,    1023, 1046529]], shape=(1024, 3))

In [4]:
from utilities.munkres import Munkres
import numpy as np
import time 
matrix_cost = np.random.random((200,100))

print(np.shape(matrix_cost))

m = Munkres()

t1 = time.time()
solution = m.compute(matrix_cost)
tstop = time.time()-t1

print(np.shape(solution))
print("time taken to compute solution:", tstop)

(200, 100)
(100, 2)
time taken to compute solution: 2.574815034866333


In [ ]:
from scipy.optimize import linear_sum_assignment
t1 = time.time()
solution2 = np.transpose(linear_sum_assignment(matrix_cost))
tstop = time.time()-t1

print(np.shape(np.transpose(solution2)))
print("time taken to compute solution:", tstop)

(2, 200)
time taken to compute solution: 0.000843048095703125


In [ ]:
print(solution == solution2)


[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  T

In [ ]:
print(solution==best)

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False False]
 [False Fa

In [ ]:
from utilities.ddm import ddm 
from scipy.io.wavfile import write, read

signal_test = read("/Users/colas/Documents/Programmation/Python/Fast_Partial_Tracking_Python/data/sound/Sin8_A220Hz.wav")




win = np.hanning(self.N)
winD = np.gradient(win)
Ndft = self.Ndft
ndft = np.arange(0,Ndft,1)
omega = 2 * np.pi * ndft/Ndft
t = np.arange(self.N) / self.fs

n_center = (self.N - (self.N % 2)) // 2
        centering = np.exp(1j * omega * n_center)
        ft_mat = np.exp(1j * np.outer(t - np.mean(t), omega[:Ndft//2]))

        n = np.expand_dims(np.arange(self.N),axis=1) - n_center
        
        p = functions.time_vector_computation(n,self.Q)
        pD = functions.derivative_time_vector_computation(n,self.Q)
        
        Rddm = self.Q*self.overSample
        Alpha, num_peaks, S = ddm.ddm(signal, self.Q, Rddm, self.G_g, win, winD, p, pD, centering, self.Ndft, ft_mat, omega)